FROM nicholasjackson/microservice-basebox

EXPOSE 8001

# Create directory for server files
RUN mkdir /<%= application_name %>

# Add s6 config
ADD s6-etc /etc/s6
RUN chmod -R 755 /etc/s6; \
chmod -R 755 /etc/s6

# Add consul template
ADD config.ctmpl /<%= application_name %>/config.ctmpl

# Add server files
ADD swagger_spec /swagger
ADD testservice /<%= application_name %>/<%= application_name %>

RUN chmod 755 /<%= application_name %>/<%= application_name %>

ENTRYPOINT ["/usr/bin/s6-svscan","/etc/s6"]
CMD []
