FROM nicholasjackson/microservice-basebox

EXPOSE 8001

# Create directory for server files
RUN mkdir /<%= application_name %>


# Add consul template
ADD config.ctmpl /<%= application_name %>/config.ctmpl
ADD entrypoint.sh /entrypoint.sh

# Add server files
ADD <%= application_name %> /<%= application_name %>/<%= application_name %>

RUN chmod 755 /<%= application_name %>/<%= application_name %>
RUN chmod 755 /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD []
